% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Jan-2017 17:48:50
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('select.mat');

x = 3.90625;

whichbar = saveVarsMat.whichbar; % <1x1 matlab.ui.Figure> unsupported class

varargin = cell(1, 3);
varargin{1} = [' ', char(10), 'Backward search of optimal feature set o' ...
               'ut of 256: 246', char(10), 'Posteriors for 10 classes: ' ...
               '10', char(10), ' '];
varargin{2} = 'position';
varargin{3} = [441 280.8 270 86.399999999999977];

inWaitbarCreate = false;

handles = saveVarsMat.handles; % <1x1 struct> unsupported class at handles.figure

clear saveVarsMat;
